meta_product_name: "IDK"
meta_title: "IDK - Break the Loop!"
meta_description: "IDK is an activity generator targeting mainly indecisive millennials. The user gets suggestions of what's happening around."
meta_image: "cover.png"
twitter_account: "@idk_lewagon"
