development:
  forest_env_secret: 38eabe0d59b6f2f73de9e94c073e426f04ad3db28b5cc451cdaa93de5ce8589a
  forest_auth_secret: FaFp_SznSoC9SnTeQJ73Yw
staging:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
production:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
